### ISSUE TITLE
Black Screen During Magic Tutorial. 

### ISSUE THREAD

**Issue by DexeronStarsurge** [vitor251093/KHDays_FM#94] opened 2024-05-17 19:23 UTC
After killing the remaining heartless after casting fire, where the game would normally(I think) transfer into a cutscenes with Larxene, the screen just turns black, and the music continues, not stopping.

**Comment by sandwichwater** [comment] 2024-05-17 20:57
what version are you using ¿ this is an older bug that has since been fixed in newer versions

**Comment by DexeronStarsurge** [comment] 2024-05-17 21:21
> what version are you using ¿ this is an older bug that has since been fixed in newer versions

0.2.1 downloaded today

**Comment by sandwichwater** [comment] 2024-05-18 05:03
huhm .. confirmed working fine on my end , what platform are you on ¿

**Comment by DexeronStarsurge** [comment] 2024-05-18 17:11
Windows 10

**Comment by DexeronStarsurge** [comment] 2024-05-22 01:38
So, tried again after a few days. Decided to redisable JIT Recompiler in CPU Emulation in the Emu settings and it worked. I had initially enabled it because cutscenes were lagging and I read somewhere it would help.

**Comment by gamesception** [comment] 2024-05-22 21:24
was enabled by default for me, but disabling it fixed the problem for me as well.

**Closed** 2024-05-22 22:11 UTC
Labels: bug, display mode issue

**Comment by DexeronStarsurge** [comment] 2024-05-23 00:05
Hopefully this is alright, but just putting this here in case anyone else finds this issue, after completing that one area, turning JIT Recompiler back on so far has worked fine.
