### ISSUE TITLE
Segfault occurs on Ubuntu 22.04

### ISSUE THREAD

**Issue by StardustSauce** [vitor251093/KHDays_FM#52] opened 2023-12-31 19:05 UTC
I'm on Ubuntu 22.04. On release 0.1.1, 0.1.0, and when compiling the current build, all versions of the emulator promptly crash on startup with the following log in terminal:

```
IPC: instance ID 10
Failed to open "/home/sauce/.config/khDaysMM/melonDS.ini" with FileMode 0x11 (effective mode "r")
Failed to open "/home/sauce/.config/khDaysMM/melonDS.11.ini" with FileMode 0x11 (effective mode "r")
Opened "/home/sauce/.config/khDaysMM/melonDS.11.ini" with FileMode 0x12 (effective mode "w")
Segmentation fault (core dumped)
```

I do not encounter this issue on windows, and can't imagine what could be going wrong on my end if it were user error.

**Comment by vitor251093** [comment] 2024-02-02 23:03
@StardustSauce this issue should now be fixed. Could you please confirm?

**Comment by StardustSauce** [comment] 2024-02-03 06:08
I'm afraid not, though it does seem to be getting further than when I created this ticket. Output from building the latest from master branch below:
```
khDaysMM 0.1.1
https://github.com/vitor251093/KHDays_FM
IPC sharedmem doesn't exist. creating
IPC: instance ID 0
Failed to open "/home/sauce/.config/khDaysMM/melonDS.ini" with FileMode 0x11 (effective mode "r")
Opened "/home/sauce/.config/khDaysMM/melonDS.ini" with FileMode 0x12 (effective mode "w")
Created a OpenGL context
GL_VENDOR: NVIDIA Corporation
GL_RENDERER: NVIDIA GeForce RTX 2060/PCIe/SSE2
GL_VERSION: 4.3.0 NVIDIA 535.154.05
GL_SHADING_LANGUAGE_VERSION: 4.30 NVIDIA via Cg compiler
MP sharedmem doesn't exist. creating
MP comm init OK, instance ID 0
Segmentation fault (core dumped)
```
Running the program will now create a window for an instant before the crash occurs.

**Comment by vitor251093** [comment] 2024-02-03 21:08
Does the same issue happens if you try to compile and run melonDS?

**Comment by StardustSauce** [comment] 2024-02-03 22:33
Building MelonDS from source results in the emulator launching and running games as expected.

**Comment by vitor251093** [comment] 2024-02-04 16:35
Could you confirm if that issue happens with our branch base_melonds. That's the branch with the melonDS version KhDays is currently based on.

I just want to confirm if the bug is entirely on our side, or if it may be fixed by merging the melonDS's most up to date source code.

**Comment by StardustSauce** [comment] 2024-02-05 02:44
Unfortunately, I can confirm that the emulator runs without error on the base-melonds branch.

**Comment by vitor251093** [comment] 2024-02-06 05:29
@StardustSauce I just realized base_melonds was some commits ahead of master. Just merged the commits from the version you got to test into the master branch. Could you confirm if the problem persists?

**Comment by StardustSauce** [comment] 2024-02-06 05:43
Can confirm, the problem is persisting with the same output to console.

**Comment by StardustSauce** [comment] 2024-02-07 08:36
The emulator has successfully launched with the configuration set to `3DRenderer=1`. I'm ingame and able to play.

Curiously, I found that no audio was output by the emulator. When I compared my default settings in khdaysMM to those from melonDS, melonDS featured a setting named `AudioBitrate` and khdaysMM had one in the same location named `AudioBitDepth`. Renaming to `AudioBitrate` caused audio to play ingame.

**Comment by vitor251093** [comment] 2024-02-07 12:18
Well, I'm not sure why it worked now, since I just added logs, but I'm not complaining xD

Out of curiosity: which value does AudioBitrate have? It seem to me that they may have changed that key name, but the default value may not be working if the config file already exists. At least, this is my current theory.

**Comment by StardustSauce** [comment] 2024-02-07 18:24
To confirm, the issue is NOT fixed, but your intuition that there could be an issue with the OpenGL implementation was correct. I can run the game in the Software renderer, but the segfault occurs in OpenGL. As for the `AudioBitrate` setting, the default value in MelonDS is 0.

**Comment by vitor251093** [comment] 2024-02-07 18:31
Regarding OpenGL, does melonDS also crashes if you enable it? Just asking to be sure that the issue is with the melonDS OpenGL implementation itself, or if it's connected to our custom shader.

If it's connected to the custom shader, I can fix it. If it's connected to the OpenGL implementation, I can try to help, by investigating and opening a PR to melonDS in case I find a solution.

**Comment by StardustSauce** [comment] 2024-02-07 21:40
Right, I should've mentioned it before. I encounter no issue with MelonDS's OpenGL renderer.

**Comment by vitor251093** [comment] 2024-02-07 22:23
Right. One last question: does the issue also happen with the GitHub builds (from the Actions tab), or only if you build it from the source in your machine?

Checking if the issue may be the lack of something during the building process that, for some reason, isn't considered mandatory by it, but breaks OpenGL rendering anyway.

In the meanwhile, I will add a menu option to disable KhDaysMM's shader, so we can debug if the issue is really in the shader or not.

Also, I should be making the v0.2.0 release tonight since the Windows version is already working (and it has been a long time since I made an official release), so we can include any necessary fixes for the Ubuntu build in v0.2.1 later on.

**Comment by vitor251093** [comment] 2024-03-18 23:48
@StardustSauce can you confirm if the issue still happens with the latest version in the master branch?

**Comment by StardustSauce** [comment] 2024-03-19 12:22
Confirmed! I'm ingame with the OpenGL Renderer and seeing all improvements as expected. Excellent work.

**Closed** 2024-03-19 12:37 UTC
Labels: bug
