### ISSUE TITLE
all bugs found with ui build

### ISSUE THREAD

**Issue by sandwichwater** [vitor251093/KHDays_FM#58] opened 2024-02-02 22:45 UTC
figured id just group these all in one since they all seem to be related to the latest build with ui scaling

mission mode cutscenes seem to bug out and seem to think its an ingame event
![image](https://github.com/vitor251093/KHDays_FM/assets/70611518/ac727c82-e028-46d6-9403-01a3ba4e59d8)

selecting a mission via holo missions seems to bug out and think its an ingame event
![Screenshot (1057)](https://github.com/vitor251093/KHDays_FM/assets/70611518/89ff6cfb-79fc-4600-84da-22340036d151)

the game seems to be squished , ui is fine (unsure what causes it , but using the old widescreen cheat seems to fix it)
![image](https://github.com/vitor251093/KHDays_FM/assets/70611518/08a78750-36ce-42b1-b666-a3def1fbf667)
vs proper 16:9 using the old widescreen cheat
![image](https://github.com/vitor251093/KHDays_FM/assets/70611518/7651e850-4a5c-4cf0-b91b-c90483572ea3)

on the opposite side sometimes when launching the game it seems to stretch , again ui is fine (old widescreen cheat fixes this too)
![image](https://github.com/vitor251093/KHDays_FM/assets/70611518/4a71b977-c8b6-415a-b5c1-cd0697494285)

skipping the information bar in challenge mode seems to bug out for a split second (unsure what causes this as it doesnt happen in story mode or mission mode)

https://github.com/vitor251093/KHDays_FM/assets/70611518/f49c5ad1-888e-49ef-ab3a-22a1266b7ab2

lock on doesnt display correctly (enemy health gets slightly cut off at the bottom as well but thats a more minor isssue)
![image](https://github.com/vitor251093/KHDays_FM/assets/70611518/96e08dfc-b462-4c2a-864b-0b8c11b254df)

command menu gets slightly cut off to the right (for reference i have 24 fires equipped , the 4 gets cut off)
![image](https://github.com/vitor251093/KHDays_FM/assets/70611518/4f3f7bf4-d328-43df-84ac-cfa40af14cf6)

double bug :
1. changing graphics settings reverts back to stretched ds size menu but reverts when paused and unpaused , doing anything opengl related really ... changing settings , using speedup , etc . i dont know how many users as a whole this would affect but just to be on the safe side maybe it should be looked at
2. so , i cant tell if this was intentional or not , but changing ingame render resolution changes the size of the ui . it works really well for scaling but for people who may want to play on higher resolutions with a bigger ui , or a smaller resolution but dont want the ui taking up literally half their screen (could cause issues with multiplayer or missions with multiple party members) , it might be a bit of a problem . could it be possible to add separate menu scaling ¿

https://github.com/vitor251093/KHDays_FM/assets/70611518/d05f055b-90ed-47c2-845a-a278010d3569.mp4

this also affects elements such as mission sigils and the death counter deaths
![image](https://github.com/vitor251093/KHDays_FM/assets/70611518/82f79bb5-8dba-4f38-84d5-1951b14f0b1e)
![image](https://github.com/vitor251093/KHDays_FM/assets/70611518/76c06931-5c86-44a1-8111-d314f5a8ee1f)

hud doesnt work properly with 3-4 players
![image](https://github.com/vitor251093/KHDays_FM/assets/70611518/55fec6df-6c9a-4bfc-9a1b-65b77765d547)

im not sure if this was introduced with the ui update but it doesnt behave properly so i figure id mention it anyway

https://github.com/vitor251093/KHDays_FM/assets/70611518/e436dc53-06ef-4221-b169-686f224e839b.mp4

this is all ive found so far , will report back if more scenarios are broken

**Comment by sandwichwater** [comment] 2024-02-03 00:35
multiplayer results menu seems to bug out as well

https://github.com/vitor251093/KHDays_FM/assets/70611518/31964106-6029-48b1-95ae-675924ce7794

**Comment by sandwichwater** [comment] 2024-02-03 00:46
dialogue boxes also get cut off (doesnt seem to happen every time)
![image](https://github.com/vitor251093/KHDays_FM/assets/70611518/1448dbb5-d726-4147-8868-322ebe884bbe)

seems to also be affected by size as well
![image](https://github.com/vitor251093/KHDays_FM/assets/70611518/6efffffa-d714-422b-be47-622133aa99a0)

**Comment by vitor251093** [comment] 2024-02-03 18:02
I have a question regarding the "selecting a mission via holo missions seems to bug out and think its an ingame event" item. Is there a reliable way to reproduce that? I've accessed the holo missions with the saves I have a couple of times, but couldn't find a reliable way to see that happening.

Also, the videos are not playing for some reason, so I couldn't see "skipping the information bar in challenge mode seems to bug out for a split second (unsure what causes this as it doesnt happen in story mode or mission mode)". The other ones I remember watching yesterday, and will include my observations below.

The following items I will leave for the future, because based on the type of bug, they are definitively older bugs, they will be header to fix, and I don't think it would be worth to hold the update for long because of those bugs only. I will create a separate issue to handle them after I finish this one:
- im not sure if this was introduced with the ui update but it doesnt behave properly so i figure id mention it anyway
- multiplayer results menu seems to bug out as well

Let me compile the others into a textual list, adding some observations of mine:
- Mission mode cutscenes looks bugged after being confused as a regular game scene
- Auto-resolution hack is considering the startup window size only, instead of updating if it's changed
- Skipping the information bar in challenge mode seems to bug out for a split second
- "Locked on" is appearing in the middle of screen, but is incomplete
- Enemy health gets slightly cut off at the bottom
- Command Menu gets slightly cut off to the right
- Changing graphic settings should preserve the current game scene and aspect ratio
- Different resolutions shouldn't change the UI size; it should only be affected by the UI scale (option to change it will be covered by #55 )
- Different resolutions aren't affecting mission sigils and the death counters
- 4th player health bar and pic aren't appearing
- Dialogue boxes also get cut off sometimes (can be reproduced during the first mission involving Roxas and Axel)

**Comment by vitor251093** [comment] 2024-02-03 20:36
Other than the items that received new issues where they can be handled in the future, all the bugs should be fixed by now. @sandwichwater can you confirm if that's the case for the latest build?

**Comment by sandwichwater** [comment] 2024-02-03 20:52
mhm ill test these out

> I have a question regarding the "selecting a mission via holo missions seems to bug out and think its an ingame event" item. Is there a reliable way to reproduce that? I've accessed the holo missions with the saves I have a couple of times, but couldn't find a reliable way to see that happening.

ill try to find what causes it yea , its so strange because it was one of the first things that i encountered , disappeared for a few hours , then came back later with no immediately apparent method to cause it so im unsure

> Also, the videos are not playing for some reason

well thats ... annoying , thanks github video player lol

**Comment by sandwichwater** [comment] 2024-02-03 22:18
yep , everything seems to be fixed !

**Closed** 2024-02-03 22:58 UTC
Labels: bug
