### ISSUE TITLE
Dual Screen breaks when finishing a challenge mission. 

### ISSUE THREAD

**Issue by barnhemich** [vitor251093/KHDays_FM#159] opened 2024-06-14 18:21 UTC
**Describe the bug**
When you complete or fail a challenge mission the dual screen effect breaks on the mission results screen and does not show you the bottom screen anymore. Making you pull the bottom screen up to advance. 

**To Reproduce**
1. Finish/Withdraw Challenge mission

**Expected behavior**
View the top and bottom screen so you can navigate away and see your rewards. 

**Screenshots**

![image](https://github.com/vitor251093/KHDays_FM/assets/45804419/ab9719aa-0e02-4acb-b86a-6d3a674cf5bd)

**Desktop (please complete the following information):**
 - OS: Windows
 - Melon Mix Version 0.3.0

**Comment by vitor251093** [comment] 2024-06-14 21:07
This is a duplicate of #152, so we are going to deal with the bug there

**Closed by vitor251093** 2024-06-14 21:07 UTC
Labels: bug, duplicate
